kit:
  name: "PetClinic"
  link: https://github.com/qubell/starter-java-web
  environment: "580a0422a826436971cf14bc"
  applications:
    - name: "Application Server"
      manifest: https://raw.github.com/qubell-bazaar/component-tomcat-dev/1.0-34p/component-tomcat-dev.yml
      service: "true"
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      docs
