kit:
  name: "PetClinic"
  link: https://github.com/qubell/starter-java-web
  environment: "57023ab2e4b0f129931b7bb7"
  applications:
    - name: "PetClinic"
      manifest: https://raw.github.com/qubell-bazaar/starter-java-web/1.1-37p/starter-java-web.yml
      service: "true"
    - name: "Database"
      manifest: https://raw.github.com/qubell-bazaar/component-mysql-dev/1.0-34p/component-mysql-dev.yml
      service: "true"
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      docs
