kit:
  name: "PetClinic"
  link: https://github.com/crazzysun/starter-java-web
  environment: "580a0422a826436971cf14bc"
  applications:
    - name: "Application Server"
      manifest: https://raw.githubusercontent.com/crazzysun/starter-java-web/master/empty.yml
      service: "true"
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      docs
